import { Fraunces, Inter, Italianno, Libre_Baskerville, Merriweather, Playfair_Display, Tinos } from "next/font/google";
import "./globals.css";

const inter = Merriweather({ subsets: ["latin"],weight:['300'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
